### ISSUE TITLE
Doesn't load offers

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#10]
Hello. When I use `$steam->getTradeOffers()->getSentOffers()` it returns empty array (`[]`). I debugged data that returns `steamCommunity->cURL()` and it was like this: http://prntscr.com/9tyweg 
So script cannot parse data and DOM is empty. What's wrong?

**Comment by JohnnyFunt** [comment]
The problem with the encoding, translate response from debug in UTF-8.

**Comment by CyanoFresh** [comment]
Tried with `mb_convert_encoding($data, "UTF-8", 'auto')` - another string, but still the same. Ok, if this is problem with debugging and charset, why `getSentOffers()` returns `[]`?

**Comment by JohnnyFunt** [comment]
Try this:
$tradeOffers = $steam->getTradeOffers();
var_dump($tradeOffers->getSentOffers());

**Comment by CyanoFresh** [comment]
```
array(0) { }
```

**Comment by JohnnyFunt** [comment]
I do not know then. I have work. Check availability sent trades.

**Comment by CyanoFresh** [comment]
I moved to API loading and it works fine
