### ISSUE TITLE
Send offer to non-friend

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#12]
Hello again. How to send offer to non-friend user? I tested and discovered that I can send offer only for friend. If partner isn't a friend - steam trade error 15

**Comment by waylaidwanderer** [comment]
Are you setting the trade token?

**Comment by waylaidwanderer** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/TradeOffers/Trade.php#L68

**Comment by CyanoFresh** [comment]
@waylaidwanderer thank you. I didn't realize before for what that token. Works fine

**Comment by mruz** [comment]
> {"strError":"There was an error sending your trade offer.  Please try again later. (15)"}

I dumped response and I'm getting this for both with(out) token.

**Comment by CyanoFresh** [comment]
15 error - permission denied. Myabe some of traders cannot trade by their settings

**Comment by mruz** [comment]
@CyanoFresh you were right, thanks.
