### ISSUE TITLE
Login Loop on Invalid Credentials causes "Too Many Logins" for Steam

### ISSUE THREAD

**Issue by hscanlan** [waylaidwanderer/PHP-SteamCommunity#13]
I'm just trying to implement the 2FA, but got caught in a "Login Loop" in the bot which caused my account to lock on stream. (Password wasn't invalid, I had a newtonsoft error but thats another issue.)

Just trying to figure out how I can stop that loop so it doesn't try to constantly login and end up locking my account every time while I figure out how to work with 2FA.

**Comment by hscanlan** [comment]
Sorry, this is in the wrong section .. please delete

**Comment by CyanoFresh** [comment]
You can simply close this issue
