### ISSUE TITLE
Can't login with limited account

### ISSUE THREAD

**Issue by mig4ng** [waylaidwanderer/PHP-SteamCommunity#14]
Hey! I'm trying to run the example you have here but I'm running into this issue:

Warning: file_put_contents(C:\xampp\htdocs\phpsteam\Examples/cookiefiles\MYLOGINHIDDEN.cookiefile): failed to open stream: No such file or directory in C:\xampp\htdocs\phpsteam\SteamCommunity.php on line 64

Fatal error: Uncaught exception 'Exception' with message 'Could not create cookiefile for MYLOGINHIDDEN.' in C:\xampp\htdocs\phpsteam\SteamCommunity.php:65 Stack trace: #0 C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php(19): waylaidwanderer\SteamCommunity\SteamCommunity->doLogin() #1 {main} thrown in C:\xampp\htdocs\phpsteam\SteamCommunity.php on line 65

**Comment by mig4ng** [comment]
I also tried to change / to \ since I'm currently using windows but it didn't fix it

**Comment by mig4ng** [comment]
Ok I found the problem, I can't authenticate with my limited account, do you think there is a way of loging in with a limited account?
If I set cookies manually I can see the trade offers, but after the first reload it asks for login again and I have to set cookies manually again, do you know how to bypass this?

**Comment by waylaidwanderer** [comment]
What do you mean you can't authenticate with your limited account? What exactly is the error?

As far as I know, there is no difference between logging into a normal vs limited account.

**Comment by mig4ng** [comment]
Im getting Failed to login: GeneralFailure.

**Comment by mig4ng** [comment]
My settings.json:
`{
  "cookieFilesDir": "",
  "username": "USERNAMEHIDDEN",
  "password": "PASSWORDHIDDEN"
}`

**Comment by waylaidwanderer** [comment]
Do a `var_dump($loginResponse)` on this blank line: https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/SteamCommunity.php#L128 and you'll be able to see what the Steam error actually is. Paste it here.

**Comment by waylaidwanderer** [comment]
On second thought it might be better to put it on this line instead: https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/SteamCommunity.php#L107

**Comment by mig4ng** [comment]
Do you think having password with simbols ex: \Lz3}PZuJeV?[:=xe)_T:%{Ud[F9(6JJEmf3LeqB-wp,'){J`UAQ$M(c<"']W'x can be associated with this problem?

**Comment by waylaidwanderer** [comment]
You can try changing `urlencode` to `rawurlencode` on this line (https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/SteamCommunity.php#L95) to see if it helps.

Or you can just do the `var_dump` thing I suggested and see exactly where the problem is.

**Comment by mig4ng** [comment]
Ok I think it was the special characters, I changed passwords and now it's throwing a different error:

``` php
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Enter 2FA code: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\phpsteam\Examples\ExampleBot.php on line 59
Failed to login: GeneralFailure.
```

**Comment by waylaidwanderer** [comment]
Can you do me a favour and change your password back, and do the `var_dump` like I suggested multiple times, so that I know what the issue is? It'll be helpful for others in the future as well.

As for the error you just posted, add this line to ExampleBot.php: `define('STDIN',fopen("php://stdin","r"));`.

**Comment by mig4ng** [comment]
Ok, sorry about that, there is no need for the var_dump unless you really want it I can do it, but I figured it myself, I'm just being retard and trying to run stuff on the browser instead of using the terminal/cmd to run it like "php ExampleBot.php" so I couldn't insert the 2FA code and it was crashing, I'm sorry I bothered you with my unexperience :/
By the way does this library have any documentation?

**Comment by waylaidwanderer** [comment]
Yeah I'd like to fix the password issue so a `var_dump` would be helpful. Thanks!

Not yet, I haven't had time. Most functions are pretty well commented though with phpDocs.

**Comment by mig4ng** [comment]
Yea, the code is pretty easy yo understand, I has to leave computer in a hurry and already changed my password to letters and numbers only, but if you want I can reproduce the error later :)

**Comment by waylaidwanderer** [comment]
No problem. In the meantime, if anyone else is reading this and would like to help out, feel free.

**Comment by mig4ng** [comment]
here you have the var_dump (I used an account with special characters in the password and it worked this time o.O):
`string(468) "{"success":true,"requires_twofactor":true,"login_complete":true,"transfer_urls":["https:\/\/store.steampowered.com\/login\/transfer","https:\/\/help.steampowered.com\/login\/transfer"],"transfer_parameters":{"steamid":"765611982350118","token":"EE29311667A2F35C1909FA82B9F3D8FB3EE7","auth":"b3c37ccae542d2619bbc7532b","remember_login":false,"webcookie":"3A345C1EC9E448EB686517777CFF4E69DBCB","token_secure":"20C2FE3640167ACADA8110FD8377E653C23DFB"}}"`

PS: I removed some characters from the tokens and ids for safety.

**Comment by waylaidwanderer** [comment]
Well, that doesn't appear to be the issue then. Guess we'll never know what caused it. Thanks anyway!
