### ISSUE TITLE
Error trying to execute the new ExampleBot.php

### ISSUE THREAD

**Issue by mig4ng** [waylaidwanderer/PHP-SteamCommunity#16]
I'm having this error when I try to execute the new ExampleBot.php
`Fatal error: Arrays are not allowed in class constants in C:\Users\mig4ng\php\PHP-SteamCommunity-master\SteamCommunity.php on line 19`

My current settings.json is the default one (settings.example.json) with the correct auth data of my bot account and deviceId generated with node-totp:

``` json
{
  "username": "HIDDEN_USERNAME",
  "password": "HIDDEN_PASSWORD",
  "mobileAuth": {
    "sharedSecret": "HIDDEN_SHARED_SECRET",
    "identitySecret" : "HIDDEN_IDENTITY_SECRET",
    "deviceId": "android:HIDDEN_DEVICE_ID"
  }
}
```

**Comment by CyanoFresh** [comment]
Same

**Comment by CyanoFresh** [comment]
Php 5.6

**Comment by waylaidwanderer** [comment]
You need to be running PHP 5.6+ according to http://stackoverflow.com/questions/1290318/php-constants-containing-arrays/27413238#27413238

@CyanoFresh You're probably not actually on PHP 5.6. There's no reason to be running anything older, since previous versions have reached their end-of-life.

**Comment by mig4ng** [comment]
@CyanoFresh Upgrading PHP (to version 7) as @waylaidwanderer said worked for me, try to do the same! Thanks for the help.

**Comment by CyanoFresh** [comment]
Sorry, I have 5.5.9 on remote :(
