### ISSUE TITLE
Where to get DeviceId?

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#18]
This is needed for mobile confirmations

**Comment by waylaidwanderer** [comment]
You're supposed to set it yourself. This is assuming you've linked mobile auth via SteamBot, SDA, Node, or imported from your phone. You can find the deviceId from the auth file that is generated (not sure if Node bots do that or just randomly generate one, in which case you can do the same). If none of the above, linking mobile auth via PHP-SteamCommunity is not supported yet.

**Comment by CyanoFresh** [comment]
I have extracted files from my android device(json). There is no key with "device_id" or smth. Will my ported function work? https://gist.github.com/CyanoFresh/058acbc591e0280b10fb Is deviceID important or required to be correct?

**Comment by waylaidwanderer** [comment]
In that case, the device ID is, you guessed it, the device ID of your android phone. The easiest way to get this ID is using this app: https://play.google.com/store/apps/details?id=com.evozi.deviceid&hl=en

It's best that you use the same device ID that you first linked the mobile auth with.
