### ISSUE TITLE
Invalid authenticator

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#19]
Is there any way to debug or fix this? I have this in reponse while gettings mobile confirmations. Url:
`https://steamcommunity.com/mobileconf/conf?p=android:9789e6fa-5370-3131-3d3a-ff4db1c060fc&a=76561198273015032&k=VdzVYygW3Te/s6pmo8eRFW7gEK4=&t=1455113777&m=android&tag=conf` 
And message from page:
`Invalid authenticator
It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid.`
I dont know what is wrong.

**Comment by waylaidwanderer** [comment]
Was it working before?

**Comment by CyanoFresh** [comment]
No. It's first try

**Comment by CyanoFresh** [comment]
Tried with that app https://play.google.com/store/apps/details?id=com.evozi.deviceid generating id - same result

**Comment by waylaidwanderer** [comment]
Make sure you've set both your sharedSecret and identitySecret properly as well.

**Comment by CyanoFresh** [comment]
Yeah, works well. My problem, it was wrong db query

**Comment by waylaidwanderer** [comment]
Good to hear it's working.

**Comment by CyanoFresh** [comment]
Hah. Now it shows "nothing to confirm" but in mobile I have 1 confirmation. It was working before... Is it steam issues?

**Comment by waylaidwanderer** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/MobileAuth/Confirmations.php#L24

**Comment by CyanoFresh** [comment]
I understand but I am reloading page for 5 minutes. Sometime it returns "Invalid authenticator"

**Comment by CyanoFresh** [comment]
Created trade by this library and it is showing now :| I don't know what is this.

**Comment by CyanoFresh** [comment]
So I understood it. When the mobile Steam is opened in android - there will be no confirmations in this library. and vice versa

**Comment by waylaidwanderer** [comment]
Are you using the same device ID for this lib?

**Comment by CyanoFresh** [comment]
I don't know how to get deviceId that uses Steam on my phone. Is this same as https://play.google.com/store/apps/details?id=com.evozi.deviceid generates?

**Comment by waylaidwanderer** [comment]
Yes. The app is not generating a Device ID, but rather showing you the Device ID of your phone.

Edit: needs to be formatted as `android:XXXXXXXXXXXXX` I think.

**Comment by waylaidwanderer** [comment]
Actually, what you may need is the UUID of the android device, formatted as `android:UUID_HERE`. [This app](https://play.google.com/store/apps/details?id=com.feaws.deviceid) provides it, so try that value instead.

**Comment by CyanoFresh** [comment]
What about iOS?

**Comment by waylaidwanderer** [comment]
No clue in that case.

**Comment by CyanoFresh** [comment]
Not working for device with ios. All Secrets are set properly

**Comment by CyanoFresh** [comment]
And another question. What to do with this http://prntscr.com/a2bt6d? This is response from steam when I am trying to load confiramtions and other actions

**Comment by CyanoFresh** [comment]
Fixes by adding `curl_setopt($ch, CURLOPT_ENCODING, "gzip");` in doLogin() method

**Comment by waylaidwanderer** [comment]
Make a new issue for this.

**Comment by CyanoFresh** [comment]
ok. I thought it was related

**Comment by tallesdantas** [comment]
Cyano , can you give us the php code that does this authentication and how did you got these parameters ?, 
thanks a lot man

**Comment by CyanoFresh** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/tree/master/MobileAuth look at this files

**Comment by tallesdantas** [comment]
cyano , i have already a bot that doest everything but isnt able to confirm, can you please givme just the auth , i cant figure out how to call it =/ , i just need the confirmation

**Comment by CyanoFresh** [comment]
I also don't understand how it works. Thanks @waylaidwanderer for his job

**Comment by timmy78** [comment]
I have the same issue here.

I have this message in response when I [fetch the confirmations](https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/MobileAuth/Confirmations.php#L34)

```
Invalid authenticator It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid.
```

The fetch confirmations only **works half the time** :sob: 

My sharedSecret, identitySecret and deviceId are correct because the createTrade works.

Can anyone help me ?

Thanks !

**Comment by h1100e** [comment]
I have the same problem.Could you tell me how to solve it?

**Comment by timmy78** [comment]
We moved all to Node JS libraries and it works fine !

https://github.com/DoctorMcKay/node-steamcommunity
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager

**Comment by tabuna** [comment]
**+1**
Recently only returns void
(There is nothing to confirm)
Who can help me?

**Comment by faginet** [comment]
Error confirm mobile
> Invalid authenticator
It looks like your Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes. This could be caused by an inaccurate clock or bad timezone settings on your device. If your time settings are correct, it could be that a different device has been set up to provide the Steam Guard codes for your account, which means the authenticator on this device is no longer valid.
