### ISSUE TITLE
Unexpected response from Steam

### ISSUE THREAD

**Issue by JohnnyFunt** [waylaidwanderer/PHP-SteamCommunity#2]
Hi!

I have a bug:
PHP Fatal error:  Uncaught exception 'waylaidwanderer\SteamCommunity\SteamException' with message 'Unexpected response from Steam.' in /var/www/mydir/SteamCommunity.php:236\nStack trace:\n#0 /var/www/max-frag.ru/SteamCommunity.php(49): waylaidwanderer\SteamCommunity\SteamCommunity->_setSession()\n#1 /var/www/mydir/Examples/ExampleBot.php(18): waylaidwanderer\SteamCommunity\SteamCommunity->__construct('mylogin', 'mypassw...', '/var/www/mydir...')\n#2 {main}\n  thrown in /var/www/mydir/SteamCommunity.php on line 236

Please help find a solution.

**Comment by waylaidwanderer** [comment]
You're supposed to catch the exception and handle it. Most likely Steam was down at the time.

**Comment by JohnnyFunt** [comment]
Yes, you were right, I used a proxy, which falls off. Thank you.

Prompt what cookies must be specified in the file?

**Comment by waylaidwanderer** [comment]
> Prompt what cookies must be specified in the file?

Sorry, not quite sure what you're asking here.

**Comment by JohnnyFunt** [comment]
Sorry for my English.

I need to add a cookie to a file?

**Comment by waylaidwanderer** [comment]
The cookies will be saved in the directory you set (e.g. `/var/www/mydir...`). You don't need to do anything.

Refer to ExampleBot.php for examples, and read the PHPDocs for the functions in SteamCommunity.php.
