### ISSUE TITLE
isOurOffer method should be renamed to getIsOurOffer

### ISSUE THREAD

**Issue by botsolutions** [waylaidwanderer/PHP-SteamCommunity#20]
waylaidwanderer\SteamCommunity\TradeOffers\TradeOffer

in this case the "is" word is not the part of the method name, it's from the name of property.

Please fix

**Comment by waylaidwanderer** [comment]
I'm not "fixing" this. To keep consistent naming conventions, functions that return a boolean will be prefixed with "is", even if the variable also starts with the same word.
