### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by xenkocz** [waylaidwanderer/PHP-SteamCommunity#21]
$ composer require waylaidwanderer/php-steamcommunity

  [InvalidArgumentException]
  Could not find package waylaidwanderer/php-steamcommunity at any version for your minimum-stability (stable). Check
   the package spelling or your minimum-stability
.................................................................................................................................................................

any idea?

**Comment by waylaidwanderer** [comment]
`composer require waylaidwanderer/php-steamcommunity dev-master`

**Comment by lpasek** [comment]
Please add this to README.md for another users

**Comment by CyanoFresh** [comment]
it's composer related situation and depends on your project setup
