### ISSUE TITLE
Unexpected response from Steam

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#24]
Steam response:
![Screen](http://i.imgur.com/tYZD7tT.jpg)
Before was working well but now I have this issue. Fixes by adding this to all curl requests by this library:

```
curl_setopt($ch, CURLOPT_ENCODING, "gzip");
```

**Comment by waylaidwanderer** [comment]
Does it affect non-gzipped responses?

**Comment by CyanoFresh** [comment]
I am bad at curl, requests and api, so I don't understand what are you talking about. It works well on my 2 hosts. I found solution on stackoverflow

**Comment by CyanoFresh** [comment]
Now tried at remote host without fix - all works. Don't know what is this.

**Comment by waylaidwanderer** [comment]
Anyone else experiencing this problem?

**Comment by CyanoFresh** [comment]
Now stable. I think it's OS settings or network bug
