### ISSUE TITLE
Don't set mobile session, if not needed

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#28]
If mobile confirmations isn't needed in my code - why it mobile logins? Please add some boolean parameter with optional mobile login - it will save some time(mobile auth takes 1/2 of all auth time). And will be better to do mobile auth manually and optionally after simple doLogin() in code.

**Comment by CyanoFresh** [comment]
I want this because script goes in infinite loop and crashes with "Maximum execution time of 180 seconds exceeded". It goes after mobile `__construct()` (SteamCommunity constructor.) So how to solve this? (issue #29 )

**Comment by waylaidwanderer** [comment]
This is already the case, mobile session is not set if not needed: https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/SteamCommunity.php#L66

**Comment by CyanoFresh** [comment]
Yes, I can not fill `mobileAuth` but then I will not be able to login with steam gruard codes. So sad :(

**Comment by CyanoFresh** [comment]
I think, SteamGuard class can be moved from Mobile Auth, because it uses only sharedSecret and related to regular login

**Comment by waylaidwanderer** [comment]
If you need to generate 2FA codes doesn't that mean you also need to login via mobile for stuff like trade confirmations anyway?

**Comment by CyanoFresh** [comment]
if I only want to send trade to another user (without my items) or only get wallet balance?

**Comment by waylaidwanderer** [comment]
Open a separate issue for this, I'm willing to change it like you suggested.
