### ISSUE TITLE
Create Trade

### ISSUE THREAD

**Issue by JohnnyFunt** [waylaidwanderer/PHP-SteamCommunity#3]
Hi!

I create trade:

$trade = $tradeOffers->createTrade(XXXXXXXX);
$trade->addMyItem(730, 2, XXXXXXXXXX);
var_dump($trade->sendWithToken('XXXXXXXX'));

I get the answer: int(0)
Why Steam sends an empty response?

**Comment by waylaidwanderer** [comment]
Make sure you're passing in the account ID in createTrade, not the SteamID.

**Comment by JohnnyFunt** [comment]
I bring PartnerID of TradeURL, and where do I find AccountID?

**Comment by waylaidwanderer** [comment]
PartnerID is the same thing as AccountID so it should be the correct one. 

Try debugging the response Steam gives here: https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/TradeOffers/Trade.php#L87

**Comment by JohnnyFunt** [comment]
I did debug response CURL, the answer was int (0). I later send you debug the code.

P.S. I am very grateful for the work done. I wish you continued success!

**Comment by waylaidwanderer** [comment]
Seems like it's a Steam issue, perhaps? Or maybe you are adding an item to the trade offer from the wrong inventory?

Thanks! Hope you're finding it useful.

**Comment by mruz** [comment]
I also have this answer `int(0)`. If I dump response I get:
`string(4) "null"`

**Comment by timmy78** [comment]
Same error, `int(0)` :disappointed: 

You need to reopen the issue.

**Comment by CyanoFresh** [comment]
Same issue only on one my bot account. How to debug this?

**Comment by mruz** [comment]
@CyanoFresh what the difference between accounts? Settings (profile and inventory privacy), do you have someone in friend list, do you have some item in the inventory?

**Comment by mruz** [comment]
I still have this problem, @waylaidwanderer any help? and could you reopen this issue?

**Comment by timmy78** [comment]
It works, the problem was because of the new stream hold delays (escrow date).

**Comment by mruz** [comment]
For me, helps setting `$mobile = true` on construct.
