### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ElitEXE** [waylaidwanderer/PHP-SteamCommunity#34]
Whenever I do:

```
$steam = new SteamCommunity(...);
$result = $steam->doLogin();

if ($result != LoginResult::LoginOkay){
    /** Not logged in... ;-; **/
    echo ";-;" . PHP_EOL . PHP_EOL . $result . PHP_EOL;
}

if ($result == LoginResult::LoginOkay){
    if ($steam->getSteamId() == "1234567898765"){
        $tradeOffers = $steam->tradeOffers();

        $trade = $tradeOffers->createTrade(...);

        $trade->addOtherItem(730, 2, "5249722517");

        echo var_dump($trade->send("AbCdEfGh"));
    }
}
```

Steam always returns an empty response: `int(0)`

If I set `curl_setopt($ch, CURLOPT_FAILONERROR, true);`, I always get `The requested URL returned error: 400 Bad Request`

I do not know where the error is exactly, but to the best of my ability this means that the sent data was formatted incorrectly or the headers didn't match.

I checked, and saw that the data being sent wasn't formatted properly. The leading '{' and trailing '}' were missing most of the time. I assume this is because `json_encode()` doesn't return what you think it does. It returns an array object, not a string like it should be. So I fixed it and urlencoded the data. (I might add a pull request with my own code that makes sure the json post data is always formatted properly- if you'd like me to, it'd be just for you to look at.)

After that, I was still getting the same `The requested URL returned error: 400 Bad Request` error. So I compared the sent data (urlENCODED and DECODED) with the same exact trade I made on the steam website itself, and saw the sent data was exactly the same.

My only assumption is that the request headers weren't EXACTLY the way steam wants them. I'm looking into adding as many of the same post headers. In the mean time I guess you could check it out, too.

I just felt like posting the issue here because I saw that others have been getting the same error using your code, but no issues of this exist on Jessecar96's code. Have you tested this yourself? If so, did you happen to get the same error but fixed it without adjusting the repository?

Any information you have would be great :)

**Comment by hodlbe** [comment]
Вместо  $trade->add**Other**Item(730, 2, "5249722517"); НАДО -  $trade->add**My**Item(730, 2, "5249722517");
