### ISSUE TITLE
Some optimizations

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#46]
Hello. @waylaidwanderer if you see this post - please reply. I need to know if this project is active. 
If so - please do some optimizations - requests are so slow (#41) or explain how does the code work (some examples)

**Comment by waylaidwanderer** [comment]
Pretty busy lately, but feel free to contribute with pull requests. The code is pretty self-explanatory. Documentation will come later when the project reaches a point I can consider "v1.0".

Duplicate of #41
