### ISSUE TITLE
[Question] What is "ask"

### ISSUE THREAD

**Issue by v0rix** [waylaidwanderer/PHP-SteamCommunity#47]
Hi, I see in the "ExampleBot.php", this lines:

```
$authCode = ask('Enter 2FA code: ');
$authCode = ask('Enter Steam Guard code from email: ');
$captchaCode = ask('Enter captcha (' . $steam->getCaptchaLink() . '): ');
```

What is the function "ask()" and where it is.

Regards

**Comment by waylaidwanderer** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/Examples/ExampleBot.php#L76

Just a function that reads command line input.
