### ISSUE TITLE
Trade onHold

### ISSUE THREAD

**Issue by ReptoxX** [waylaidwanderer/PHP-SteamCommunity#50]
Hey guys,

is there a way to check the trade (before accepting) if it get on hold?
So that the bot can automatically decline the trade if the other side doesnt use mobile-auth?

I am sorry, if it is asked before and i didnt recognized it.

Regards,
ReptoxX

**Comment by CyanoFresh** [comment]
Check the trade offer state in TradeOffer.php

**Comment by ReptoxX** [comment]
The trade offer state is 2, because it is not accepted. 
After i accepted it, it says state 11 (for onHold).
And getEscrowEndDate only works on already accepted trades, otherwise it will return 0 unfortunatly.

**Comment by ReptoxX** [comment]
Anyway i get another error: Uncaught exception 'waylaidwanderer\SteamCommunity\MobileAuth\WgTokenInvalidException'

**Comment by ReptoxX** [comment]
Okay i guess no one knows an solution right ?

**Comment by CyanoFresh** [comment]
You can accept trade and then cancel if it has 11 state
