### ISSUE TITLE
Looking for an example

### ISSUE THREAD

**Issue by NadirRed** [waylaidwanderer/PHP-SteamCommunity#52]
Hello,
Can someone post the code for how to :
- login
- send trade offer
  -confirme offers
- get state of a specific offer

Because i didnt find so much help in docs.
Thank you

**Comment by waylaidwanderer** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/Examples/ExampleBot.php

All three are in here.
