### ISSUE TITLE
ExampleBot.php not working

### ISSUE THREAD

**Issue by NadirRed** [waylaidwanderer/PHP-SteamCommunity#53]
hello, 
this is my first time trying this lib,
i set my login information in file settings.json and open url 
http://localhost/PHP-SteamCommunity-master/Examples/ExampleBot.php

and i got this message on the web page
`Fatal error: Class 'waylaidwanderer\SteamCommunity\SteamCommunity' not found in C:\AppServ\www\PHP-SteamCommunity-master\Examples\ExampleBot.php on line 17`

what's the problem ? 

and please ... i want to remove this

```
defined('STDIN') or define('STDIN', fopen("php://stdin","r"));

use waylaidwanderer\SteamCommunity\Enum\LoginResult;
use waylaidwanderer\SteamCommunity\MobileAuth\WgTokenInvalidException;
use waylaidwanderer\SteamCommunity\SteamCommunity;
```

and replce it with normal files include 
**i hope you tell what files should be included to examplebot to work**

**Comment by CyanoFresh** [comment]
Hello. This library is built by oop style(classes and namespaces). You cannot use this only by including. Try to learn oop and ude IDE(e.g. phpstorm)

**Comment by NadirRed** [comment]
i will try and i will post again soon :)
