### ISSUE TITLE
what is the value of "op" to confirm trade offer ?

### ISSUE THREAD

**Issue by NadirRed** [waylaidwanderer/PHP-SteamCommunity#55]
hello, 
im using this link to confirme trade offers, but i get this response from steam : 
`{"success":false}`

my links to confirme are something like this : 

```
> GET /mobileconf/ajaxop?op=op&p=android:6c82fxxxx-xxxx-f1d1-a04f-804xxxxx4e4&a=76561198087663419&k=KCDrbF/o3Ip7kxxxxxxMoHUw=&t=1470407455&m=android&tag=allow&cid=928xxx259&ck=176470xxxxxx76525548 HTTP/1.1
Host: steamcommunity.com
```

i think that everything is correct ! except for the value "op" 
what should it be ?

thank you

**Comment by tabuna** [comment]
Maybe need op=allow

**Comment by CyanoFresh** [comment]
Maybe symbol "/" is not url encoded

**Comment by waylaidwanderer** [comment]
Doesn't seem related to this library.
