### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by waza123x** [waylaidwanderer/PHP-SteamCommunity#57]
I just want to tell how to install this package on PHP 7

download composer.phar 

create file composer.json

```
{
    "require": {
        "waylaidwanderer/php-steamcommunity": "dev-master"
    }
}
```

then run:

php composer.phar install

done!

command # composer require waylaidwanderer/php-steamcommunity
will not work, here is why:

```
# composer require waylaidwanderer/php-steamcommunity


  [InvalidArgumentException]
  Could not find package waylaidwanderer/php-steamcommunity at any version for your minimum-stability (stab
  le). Check the package spelling or your minimum-stability


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-de
v] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages]
 [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...


```

**Comment by waylaidwanderer** [comment]
`composer require waylaidwanderer/php-steamcommunity dev-master` is the correct, full command since the package does not have a 1.0.0+ version. I'll update the docs when I can.

**Comment by rumblefrog** [comment]
Derp, I didn't see the dev-master part on packagist
