### ISSUE TITLE
Do not send trade if your account no friends.

### ISSUE THREAD

**Issue by Andersenas** [waylaidwanderer/PHP-SteamCommunity#63]
If the user to whom I want to send a trade is not added to your friends that trade is not sent.

**Comment by grandrr** [comment]
I think you can send trade offer only your friends... Try send trade offer to some who is not your friend in steam web interface... I think i cant do this

**Comment by Andersenas** [comment]
У меня есть 2 акаунта и я тестировал через них! Если в друзьях есть трейд доходит если нет то нет!

**Comment by grandrr** [comment]
Так так і повинно бути... Наскільки я знаю в стімі не можна робити трейд оффер користувачам із яким ти не друзі

**Comment by Andersenas** [comment]
Можно нужно только понять как

**Comment by grandrr** [comment]
ну... якщо дізнаєшся - напиши як

**Comment by Andersenas** [comment]
OK

**Comment by Andersenas** [comment]
Any idea why the trade does not come?

**Comment by CyanoFresh** [comment]
через ссылку оф трейда. При отправке трейда нужно указать токен из этой ссылки.

**Comment by Andersenas** [comment]
Спасибо я не видел ответа вашего и сам его нашёл)
