### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by theosanonym** [waylaidwanderer/PHP-SteamCommunity#65]
Hi!

We would like to install PHP-SteamCommunity library to our system, but displays error.
What do we have to do to install the library correctly?

The issue is:
root@dev /path/to/SteamCommunity # composer require waylaidwanderer/php-steamcommunity dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package waylaidwanderer/php-steamcommunity No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
root@dev /path/to/SteamCommunity # cat composer.json
{
    "name": "waylaidwanderer/php-steamcommunity",
    "description": "A PHP library for interacting with the Steam Community website (steamcommunity.com)",
    "require": {
        "phpseclib/phpseclib": "^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.14"
    },
    "autoload": {
        "psr-4": {
            "waylaidwanderer\\SteamCommunity\\": ""
        }
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Joel",
            "email": "waylaidwanderer@live.com"
        }
    ]
}

Thanks,
theosanonym

**Comment by CyanoFresh** [comment]
there is no releases. Use dev-master as version

**Comment by theosanonym** [comment]
Hi

We are using dev-master version.
The code: composer require waylaidwanderer/php-steamcommunity dev-master
Is that okay, or there is another way? Please help

**Comment by CyanoFresh** [comment]
what is your minimum stability in composer json?

**Comment by waylaidwanderer** [comment]
The package doesn't officially have a release version yet so using `dev-master` is the only way for now.

**Comment by theosanonym** [comment]
Thanks all the replies, we have finally solved the problem, the lib is working fine.
