### ISSUE TITLE
what is the token？

### ISSUE THREAD

**Issue by 7gugu** [waylaidwanderer/PHP-SteamCommunity#69]
var_dump($trade->sendWithToken('token'));
Beacuse lack of the documents,I don't know what is the token and how to get? Thanks

**Comment by waylaidwanderer** [comment]
It's the trade offer token.

**Comment by CyanoFresh** [comment]
From trade offer url:
```
https://steamcommunity.com/tradeoffer/new/?partner=194406658&token=GsvgsDs
```
From the example it's `GsvgsDs`
