### ISSUE TITLE
How can I confirm an offer?

### ISSUE THREAD

**Issue by Tap0g** [waylaidwanderer/PHP-SteamCommunity#70]
How can I confirm an offer?
this does not work
...
$Tradeid = '111';
$tradeOffers = $steam->tradeOffers();
$tradeOffers-> acceptTrade ($Tradeid);
...

**Comment by waylaidwanderer** [comment]
https://github.com/waylaidwanderer/PHP-SteamCommunity/blob/master/Examples/ExampleBot.php#L57-L66
