### ISSUE TITLE
Confirm offer by id

### ISSUE THREAD

**Issue by Cosolom** [waylaidwanderer/PHP-SteamCommunity#72]
I need accept mobileAuth confirmation by offer id. Now i need fetch all confirmation and apply getConfirmationTradeOfferId for each to find which confirmation for my offer id. But offer id already placed on page with confirmations in attribute data-creator. Can we add this field to Confirmation object? I can create patch for this

**Comment by waylaidwanderer** [comment]
Feel free to make a pull request, yeah

**Comment by Cosolom** [comment]
#73

**Comment by waylaidwanderer** [comment]
Closed with https://github.com/waylaidwanderer/PHP-SteamCommunity/pull/73
