### ISSUE TITLE
How to automatically confirm the trade?

### ISSUE THREAD

**Issue by JohnnyFunt** [waylaidwanderer/PHP-SteamCommunity#9]
As I understand it, is needed to confirm the trade "identity secret" key.
Your code does not have this feature?

**Comment by waylaidwanderer** [comment]
Not yet. That's on the to-do list.

**Comment by JohnnyFunt** [comment]
https://github.com/GaletskyIvan/steamcommunity-mobile-confirmations/blob/master/index.js
I can take an example of this code and put it in php?

**Comment by waylaidwanderer** [comment]
Feel free to make a pull request if you figure it out.

**Comment by advocaite** [comment]
what is the main issue for this to be ported is it the confirmation code generations cause 
this could help with it.
https://github.com/MarlonColhado/SteamGenerateMobileAuthPHP
i to would love to see this ported over

**Comment by JohnnyFunt** [comment]
advocaite, this function has received the confirmation code 2FA, but does not confirm the trade.
Add this to yourself is not a problem.

**Comment by JohnnyFunt** [comment]
I understand what you're saying. Yes, this code can be used as a basis for writing auto confirmation of trades.

**Comment by advocaite** [comment]
yeah i was only trying to show referance to something similar it would be a nice feature to have with this library that is all

**Comment by CyanoFresh** [comment]
Is someone working on this now?

**Comment by JohnnyFunt** [comment]
No, there is no time.

**Comment by CyanoFresh** [comment]
https://gist.github.com/CyanoFresh/058acbc591e0280b10fb function for getting deviceID which is required in confirmations

**Comment by CyanoFresh** [comment]
https://github.com/Top-Cat/EscrowTF nice library. Can be used for porting

**Comment by CyanoFresh** [comment]
Failed while I was porting mobile confirmations. Can someone do it? I have no thinks how to do it.

**Comment by waylaidwanderer** [comment]
@advocaite I just added code to generate 2FA codes based on the code from your link and the C# SteamAuth project. https://github.com/waylaidwanderer/PHP-SteamCommunity/commit/cc38e082d0a48110ad4a85af2d1324107d9e3a45

I will be working on mobile confirmations once I have time.

**Comment by botsolutions** [comment]
I can see you just added the support for generating steam guard codes. Good job.
Finally, I can remove my ugly code haha.

Can we get an estimation of when we should expect the support for confirming the tradeoffers using identity_secret as a source?

**Comment by CyanoFresh** [comment]
Yeah, same question as @botsolutions . Thanks for your work. It's great. But this feature is so important

**Comment by waylaidwanderer** [comment]
Just pushed a commit for this. I've tested it myself and it worked (was able to send and confirm a trade offer), but it may take multiple retries to retrieve confirmations sometimes (which is a Steam issue I've noted in the docs). Feel free to test and open issues if you find any bugs.
